FROM python:3.11-slim

WORKDIR /app
RUN pip install poetry

COPY pyproject.toml ./
RUN poetry config virtualenvs.create false && poetry install --only main --no-root

COPY workspace.yaml ./

# Default to running the webserver
CMD ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000", "-w", "workspace.yaml"]
